disabled_rules: # rule identifiers turned on by default to exclude from running
  - trailing_whitespace
  - multiple_closures_with_trailing_closure #SwiftUI trailing closures are making a fuss.
  - identifier_name #Identifiable protocol wants id as the property which is 2 characters. Default setup here is 3 to 40

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - "*.generated.swift"
  - HikrUITests
  - HikrTests