# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

# Base setups
workspace 'Hikr.xcworkspace'

def hikr_pods
  pod 'SwiftLint'
  pod 'R.swift'
  pod 'Firebase/Crashlytics'
  pod 'KeychainAccess'
end

target 'Hikr' do
  project 'Hikr.xcodeproj'
  hikr_pods

end

# Framework
target :HikrNetworking do
    project '../Framework/HikrNetworking/HikrNetworking.xcodeproj'
    pod 'KeychainAccess'
    target 'HikrNetworkingTests' do
        inherit! :complete
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
            config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = "YES"
        end
    end
end
