# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    
  end
end

platform :ios do
    desc "Distribute app to firebase"
    lane :distribute do
        build_ios_app(...) # build_ios_app is a built-in fastlane action.

        firebase_app_distribution(
            app: "1:123888963201:ios:910a8339760a04589d8780",
            testers: "jan.bjelicic@gmail.com",
            release_notes: "Lots of amazing new features to test out!"
        )

    end
end